version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14.17
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run build
          command: npm run build
      - run:
          name: Netlify deploy preview
          command: ./bin/netlify-deploy.sh
